version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: US/Eastern
  open-pull-requests-limit: 10
  reviewers:
  - AmitPr
  assignees:
  - AmitPr
  ignore:
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: uhtml
    versions:
    - 2.4.1
    - 2.4.2
    - 2.5.3
    - 2.5.4
    - 2.6.0
    - 2.6.2
    - 2.7.1
    - 2.7.2
  - dependency-name: katex
    versions:
    - 0.13.0
    - 0.13.1
    - 0.13.2
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: typedoc
    versions:
    - 0.20.20
    - 0.20.23
    - 0.20.24
    - 0.20.25
    - 0.20.27
    - 0.20.28
    - 0.20.29
    - 0.20.30
    - 0.20.32
    - 0.20.33
    - 0.20.34
    - 0.20.35
  - dependency-name: "@types/marked"
    versions:
    - 1.2.2
    - 2.0.0
    - 2.0.1
  - dependency-name: typescript
    versions:
    - 4.1.4
  - dependency-name: marked
    versions:
    - 1.2.9
